### ISSUE TITLE
"Aw, Snap!" Error in Google Chrome

### ISSUE THREAD

**Issue by matiasdecarli** [ScottHamper/Cookies#43] opened 2015-04-28 11:53 UTC
Since i've started using this plugin, I'm seeing more and more this screen. Is there any known issue that causes this?

![screen shot 2015-04-28 at 08 50 16](https://cloud.githubusercontent.com/assets/2442390/7368953/c0baf65e-ed83-11e4-88d9-638ca74802b1.png)

Once it happens, I have to close & open the tab again. Refresh doesnt work.

Thanks in advance

**Comment by ScottHamper** [comment] 2015-04-28 17:39
Nope! No known issue. Cookies.js isn't really doing a whole lot, either, so I am skeptical that the issue is actually being caused by the library (unless it's some weird interaction with another third party thing).

If you find a reliable way to reproduce an issue, let me know!

**Comment by mkay581** [comment] 2015-05-07 20:38
I'm actually experiencing this too. And only thing I've changed before seeing it is start using this library. I'll investigate further....

**Comment by mkay581** [comment] 2015-05-07 20:42
Hey @matiasdecarli were you using browserify when you reported this issue?

**Comment by matiasdecarli** [comment] 2015-05-07 21:01
@mkay581 Actually yes. I was using browserify. It seems like a very random thing. Did you discover anything?

**Comment by mkay581** [comment] 2015-05-07 22:17
Yeah it looks like its related to requiring the lib via browserify/commonJS --  `var Cookies = require('cookies-js');`. 

Still investigating though... will report back here when done.

**Comment by mkay581** [comment] 2015-05-08 14:15
Thanks @ScottHamper for reopening, although didn't really want to officially re-open until I confirm what the issue is. @matiasdecarli I haven't had much time to look it since my last message. Sorry. I work for an agency so I pretty much have no time to do anything else lol. I'll see if I can look at it more closely over the weekend.

**Comment by matiasdecarli** [comment] 2015-05-08 14:16
I believe this issue appears when you have the web developer tools open

**Comment by mkay581** [comment] 2015-05-22 13:25
Yeah, doesnt look like this is an issue with the package. Looks more like an issue with Chrome dev tools (when you have the console open on the "Cookies" tab).

**Comment by ScottHamper** [comment] 2015-05-22 18:17
Ok, thanks for looking into this, guys!

I'll go ahead and close the issue, but if you discover anything new we can always reopen again.

**Closed by ScottHamper** 2015-05-22 18:17 UTC

**Comment by mkay581** [comment] 2015-05-23 05:22
No problem. Surprisingly, it appears to have been a bug that is fixed in latest Chrome browser. heh.

**Comment by ScottHamper** [comment] 2015-05-23 06:20
Sweet! Glad to hear
